version: "3.9"

name: artrends
services:
  artrends_frontend:
    container_name: frontend
    image: greatpop/artrends-frontend:latest
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.docker.network=proxy"
      # HTTP
      - "traefik.http.routers.artrends-frontend.rule=Host(`frontend.artrends.ar`)"
      - "traefik.http.routers.artrends-frontend.entrypoints=web"
      - "traefik.http.routers.artrends-frontend.middlewares=test-redirectscheme"
      # HTTPS
      - "traefik.http.routers.artrends-frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.artrends-frontend-secure.rule=Host(`frontend.artrends.ar`)"
      - "traefik.http.routers.artrends-frontend-secure.tls.certresolver=artrends"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
networks:
  proxy:
    external: true
