version: "3.9"

name: artrends
services:
  artrends_frontend:
    container_name: frontend
    image: greatpop/artrends-frontend:latest
    ports:
      - "3100:3100"
networks:
  proxy:
    external: true
