version: "3.9"

name: artrends
services:
  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning  --appendonly yes --requirepass "***REMOVED_REDIS_PASSWORD***"
    volumes:
      - cache:/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - ".env"
    container_name: artrends_backend
    restart: always
    volumes:
      - ".:/app"
    networks:
      proxy:
    ports:
      - "3500:3500"
    depends_on:
      - redis
    labels:
      - "traefik.port=3500"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.backend.rule=Host(`artrends-back.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
volumes:
  cache:
    driver: local
networks:
  proxy:
    external: true
