version: "3.9"

name: artrends
services:
  redis:
    container_name: redis
    image: redis:8-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning  --appendonly yes --requirepass "${REDISPASSWORD}"
    volumes:
      - cache:/data
  backend:
    image: greatpop/artrends-backend:latest
    container_name: artrends_backend
    restart: always
    env_file:
      - ".env"
    networks:
      proxy:
    ports:
      - "3500:3500"
    depends_on:
      - redis
    labels:
      - "traefik.port=3500"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # HTTP
      - "traefik.http.routers.artrends-backend.rule=Host(`api.artrends.ar`)"
      - "traefik.http.routers.artrends-backend.entrypoints=web"
      - "traefik.http.routers.artrends-backend.middlewares=test-redirectscheme"
      # HTTPS
      - "traefik.http.routers.artrends-backend-secure.entrypoints=websecure"
      - "traefik.http.routers.artrends-backend-secure.rule=Host(`api.artrends.ar`)"
      - "traefik.http.routers.artrends-backend-secure.tls.certresolver=artrends"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
volumes:
  mongodb-data:
    name: mongodb-data
  cache:
    driver: local
networks:
  proxy:
    external: true
