import Head from "next/head";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  getGoogleTrends,
  getTwitterTrends,
  getSpotifyArtistTrends,
  getSpotifySongTrends,
  getSpotifyPodcastTrends,
  getYoutubeTrends,
} from "../services/services";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data, isLoading, error } = useQuery(["google"], getGoogleTrends);
  // const { data, isLoading, error } = useQuery(["twitter"], getTwitterTrends);
  // const { data, isLoading, error } = useQuery(
  //   ["spotifyArtists"],
  //   getSpotifyArtistTrends
  // );
  // const { data, isLoading, error } = useQuery(
  //   ["spotifySongs"],
  //   getSpotifySongTrends
  // );
  // const { data, isLoading, error } = useQuery(
  //   ["spotifyPodcasts"],
  //   getSpotifyPodcastTrends
  // );
  // const { data, isLoading, error } = useQuery(["youtube"], getYoutubeTrends);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Artrends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>ARTRENDS 🇦🇷</h1>
    </div>
  );
}
