version: "3.9"

name: artrends
services:
  workers:
    container_name: artrends_workers
    env_file: ".env"
    restart: always
    image: greatpop/artrends-workers:latest
    user: "pwuser"
    security_opt:
      - seccomp:./seccomp_profile.json
