version: "2.6"

name: artrends-workers
services:
  scrapers:
    container_name: scrapers
    build: .
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    security_opt:
      - seccomp:./seccomp_profile.json
    volumes:
      - .:/app
    ipc: "host"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
    name: mongodb-data
