version: "3.9"

name: artrends
services:
  workers:
    container_name: artrends_workers
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile.local
    user: "pwuser"
    security_opt:
      - seccomp:./seccomp_profile.json
    volumes:
      - ".:/app"
