version: "3.9"

name: artrends
services:
  workers:
    container_name: artrends_workers
    image: greatpop/artrends-workers:latest
    security_opt:
      - seccomp:./seccomp_profile.json
    ipc: "host"
