name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-workers:
    runs-on: ubuntu-latest
    name: Deploy workers if needed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Look for changes in workers
        id: changed-files-in-workers
        uses: tj-actions/changed-files@v34
        with:
          files: workers/**

      - name: Build and push new image
        if: steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DATABASE_CONNECTION_URI: ${{ secrets.DATABASE_CONNECTION_URI }}
          TRENDS_ITEM_LIMIT: ${{ secrets.TRENDS_ITEM_LIMIT}}
          GOOGLE_TRENDS_BASE_UR: ${{ secrets.GOOGLE_TRENDS_BASE_URL }}
          TWITTER_TRENDS_URL: ${{ secrets.TWITTER_TRENDS_URL }}
          SPOTIFY_TRENDS_STARTING_URL: ${{ secrets.SPOTIFY_TRENDS_STARTING_URL }}
          SPOTIFY_USER_EMAIL: ${{ secrets.SPOTIFY_USER_EMAIL }}
          SPOTIFY_USER_PASSWORD: ${{ secrets.SPOTIFY_USER_PASSWORD }}
          SPOTIFY_TOP_PODCASTS_URL: ${{ secrets.SPOTIFY_TOP_PODCASTS_URL }}
          YOUTUBE_TRENDS_URL: ${{ secrets.YOUTUBE_TRENDS_URL }}
          PORTAL_EL_DESTAPE_URL: ${{ secrets.PORTAL_EL_DESTAPE_URL }}
          PORTAL_TELAM_URL: ${{ secrets.PORTAL_TELAM_URL }}
          PORTAL_INFOBAE_URL: ${{ secrets.PORTAL_INFOBAE_URL }}
          PORTAL_CLARIN_URL: ${{ secrets.PORTAL_CLARIN_URL }}
          PORTAL_LA_NACION_URL: ${{ secrets.PORTAL_LA_NACION_URL }}
      - name: Build
        if: success() && steps.changed-files-in-workers.outputs.any_changed == 'true'
        run: | 
          docker build -f ./workers/Dockerfile -t greatpop/artrends-workers:latest ./workers --build-arg DATABASE_CONNECTION_URI="$DATABASE_CONNECTION_URI" --build-arg TRENDS_ITEM_LIMIT="$TRENDS_ITEM_LIMIT" --build-arg GOOGLE_TRENDS_BASE_UR="$GOOGLE_TRENDS_BASE_UR" --build-arg TWITTER_TRENDS_URL="$TWITTER_TRENDS_URL" --build-arg SPOTIFY_TRENDS_STARTING_URL="$SPOTIFY_TRENDS_STARTING_URL" --build-arg=SPOTIFY_USER_EMAIL="$SPOTIFY_USER_EMAIL" --build-arg=SPOTIFY_USER_PASSWORD="$SPOTIFY_USER_PASSWORD" --build-arg DATABASE_CONNECTION_URI="$DATABASE_CONNECTION_URI" --build-arg TRENDS_ITEM_LIMIT="$TRENDS_ITEM_LIMIT" --build-arg GOOGLE_TRENDS_BASE_UR="$GOOGLE_TRENDS_BASE_UR" --build-arg TWITTER_TRENDS_URL="$TWITTER_TRENDS_URL" --build-arg SPOTIFY_TRENDS_STARTING_URL="$SPOTIFY_TRENDS_STARTING_URL" --build-arg=SPOTIFY_USER_EMAIL="$SPOTIFY_USER_EMAIL" --build-arg=SPOTIFY_TOP_PODCASTS_URL="$SPOTIFY_TOP_PODCASTS_URL" --build-arg=YOUTUBE_TRENDS_URL="$YOUTUBE_TRENDS_URL" --build-arg=PORTAL_EL_DESTAPE_URL="$PORTAL_EL_DESTAPE_URL" --build-arg=PORTAL_TELAM_URL="$PORTAL_TELAM_URL" --build-arg=PORTAL_INFOBAE_URL="$PORTAL_INFOBAE_URL" --build-arg=PORTAL_CLARIN_URL="$PORTAL_CLARIN_URL" --build-arg=PORTAL_LA_NACION_URL="$PORTAL_LA_NACION_URL"
      - name: Push to docker hub
        if: success() && steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: actions-hub/docker@master
        with:
          args: push greatpop/artrends-workers:latest
      - name: Pull image and re-start container in cloud server
        if: success() && steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }} 
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          PROD_ENV: ${{ secrets.PROD_ENV }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd artrends
            cd workers
            echo ${{ secrets.PROD_ENV }} > .env
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull greatpop/artrends-workers:latest
            docker compose up -d