name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-workers:
    runs-on: ubuntu-latest
    name: Deploy workers if needed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Look for changes in workers
        id: changed-files-in-workers
        uses: tj-actions/changed-files@v34
        with:
          files: workers/**

      - name: Set up QEMU
        if: steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Docker Hub login
        if: steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: docker/login-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        if: steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./workers
          file: "./workers/Dockerfile"
          push: true
          tags: ${{secrets.WORKERS_DOCKER_IMAGE_TAG}}
      - name: Pull image and re-start container in cloud server
        if: success() && steps.changed-files-in-workers.outputs.any_changed == 'true'
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }} 
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
          WORKERS_PROD_ENV: ${{secrets.WORKERS_PROD_ENV}}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd /home/{{ secrets.PROD_HOST }}/artrends/workers
            echo -e "${{secrets.WORKERS_PROD_ENV}}" > .env
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{secrets.WORKERS_DOCKER_IMAGE_TAG}}
            docker compose up -d
  build-backend:
    runs-on: ubuntu-latest
    name: Deploy backend if needed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Look for changes in backens
        id: changed-files-in-backend
        uses: tj-actions/changed-files@v34
        with:
          files: backend/**

      - name: Build and push new image
        if: steps.changed-files-in-backend.outputs.any_changed == 'true'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DATABASE_CONNECTION_URI: ${{ secrets.DATABASE_CONNECTION_URI }}
          NODE_ENV: "production"
          REDISHOST: "host.docker.internal"
          REDISPASSWORD: ***REMOVED_REDIS_PASSWORD***
          REDISPORT: 6379
      - name: Build
        if: success() && steps.changed-files-in-backend.outputs.any_changed == 'true'
        run: | 
          docker build -f ./backend/Dockerfile -t greatpop/artrends-backend:latest ./backend --build-arg DATABASE_CONNECTION_URI="$DATABASE_CONNECTION_URI"  --build-arg NODE_ENV="$NODE_ENV" --build-arg REDISHOST="$REDISHOST" --build-arg REDISPASSWORD="$REDISPASSWORD" --build-arg REDISPORT="$REDISPORT"   
      - name: Push to docker hub
        if: success() && steps.changed-files-in-backend.outputs.any_changed == 'true'
        uses: actions-hub/docker@master
        with:
          args: push greatpop/artrends-backend:latest
      - name: Pull image and re-start container in cloud server
        if: success() && steps.changed-files-in-backend.outputs.any_changed == 'true'
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd /home/ACHER/artrends/backend
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull greatpop/artrends-backend:latest
            docker compose up -d